### PR TITLE
fix: upgrade Node from 12 to 14

### PR DESCRIPTION
**Pull request by theneva**
Hi! :wave: Node 14 is LTS so it makes sense to use it :smile:

### CODE REVIEW

**Comment by ivarconr** [comment]
Yes it does, but we will not do the official switch before Unleash v4.x.

**Comment by theneva** [comment]
Fair enough. I take it you're not interested in publishing both a Node 12 and a Node 14 version for the image, and tacking on `-node14` or something to the end of the Node 14 version's tag?

**Comment by ivarconr** [comment]
I would be open for that, but I would like that to be an automated process. 

Would you be open to create the necessary tooling to release all the different versions?

**Comment by theneva** [comment]
Yep! I'll send a tooling PR hopefully today :smile:

**Comment by theneva** [comment]
@ivarconr I submitted #36 "today" in the sense of "in the next 24 hours" :smile:

**Comment by theneva** [comment]
This is no longer needed because of #36 :smile:

**Pull request closed without merging**
