### PR TITLE
feat: securing unleash with azure AD

### PR DESCRIPTION
**Pull request by ZanMarolt**
Consider adding azure passport package into the docker image by default for companies which use azure.

We would love to have this inside the docker image by default.

See my implementation example here: https://github.com/Unleash/unleash-examples/pull/28

Thanks!

### CODE REVIEW

**Comment by ivarconr** [comment]
We need to evaluate any dependency quite strictly against voulnearabilties and also we want to provide arm based images, and I see the azure passport brings along bcrypt, which we recently replaced in Unleash. 

Is there any other ways you can get this dependency in without having it as an actual dependency in this docker image?

**Comment by ZanMarolt** [comment]
There seem to be alternative like: http://www.passportjs.org/packages/passport-azure-ad-oauth2/

However all of the ones I checked are either unmaintained or come from unknown sources, so in the end decided to use the one provided by Microsoft instead. Was there a security or legal issue you had with bcrypt? 🤔

**Comment by ivarconr** [comment]
> Was there a security or legal issue you had with bcrypt?

No it was causing issues running on ARM because of the node-gyp dependency. 
https://github.com/Unleash/unleash/issues/1108

**Comment by ZanMarolt** [comment]
I see, I don't see `bcrypt` package being introduced within this PR though 🤔 

```
/unleash/node_modules $ ls -al | grep bcrypt
drwxr-xr-x    2 root     root          4096 Mar 17 14:57 bcrypt-pbkdf
drwxr-xr-x    9 root     root          4096 Mar 17 14:57 bcryptjs
```

Am I missing something? 

I have a M1 macbook and have had no issues building the docker image. I am happy to test something if needed 😉 

Thanks!

**Pull request closed without merging**
