### PR TITLE
Fix: Add dependency for securing unleash

### PR DESCRIPTION
**Pull request by evanstucker-hates-2fa**
Adding all packages needed by examples here: https://github.com/Unleash/unleash/tree/master/examples

### CODE REVIEW

**Comment by ivarconr** [comment]
could you elaborate how you plan to use these dependency in a real setup?

**Comment by evanstucker-hates-2fa** [comment]
I am currently running Unleash using Google authentication. I had to fork this docker repo and add the "@passport-next/passport" and "@passport-next/passport-google-oauth2" packages. Similarly, anyone using Keycloak or basic-auth will need these packages to use this Docker image.

See my fork here: https://github.com/evanstucker-hates-2fa/unleash-docker/commit/97461bb0d584e89891fea8a46344d7b8359c7c9c

**Comment by ivarconr** [comment]
But how do you add the google auth logic? Could you write a small example of that?

**Comment by evanstucker-hates-2fa** [comment]
I created a new index.js that was mainly copy/pasted from examples here:
* https://github.com/Unleash/unleash/tree/master/examples
* https://unleash.github.io/docs/securing_unleash
Here's my current index.js:
`      'use strict';
      
      const unleash = require('unleash-server');
      const passport = require('@passport-next/passport');
      const GoogleOAuth2Strategy = require('@passport-next/passport-google-oauth2');
      
      const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
      const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
      const GOOGLE_CALLBACK_URL = process.env.GOOGLE_CALLBACK_URL;
      const sharedSecret = process.env.SHARED_SECRET;
      
      passport.use(
        new GoogleOAuth2Strategy(
          {
            clientID: GOOGLE_CLIENT_ID,
            clientSecret: GOOGLE_CLIENT_SECRET,
            callbackURL: GOOGLE_CALLBACK_URL,
          },
          (accessToken, refreshToken, profile, cb) => {
            cb(
              null,
              new unleash.User({
                name: profile.displayName,
                email: profile.emails[0].value,
              }),
            );
          },
        ),
      );
      
      function googleAdminAuth(app) {
        app.use(passport.initialize());
        app.use(passport.session());
        passport.serializeUser((user, done) => done(null, user));
        passport.deserializeUser((user, done) => done(null, user));
      
        app.get(
          '/api/admin/login',
          passport.authenticate('google', { scope: ['email'] }),
        );
        app.get(
          '/api/auth/callback',
          passport.authenticate('google', {
            failureRedirect: '/api/admin/error-login',
          }),
          (req, res) => {
            res.redirect('/');
          },
        );
      
        app.use('/api/client', (req, res, next) => {
          if (req.header('authorization') !== sharedSecret) {
            res.sendStatus(401);
          } else {
            next();
          }
        });
        app.use('/api/admin/', (req, res, next) => {
          if (req.user) {
            next();
          } else {
            return res
              .status('401')
              .json(
                new unleash.AuthenticationRequired({
                  path: '/api/admin/login',
                  type: 'custom',
                  message: `You have to identify yourself in order to use Unleash. Click the button and follow the instructions.`,
                }),
              )
              .end();
          }
        });
      }
      
      const options = {
        enableLegacyRoutes: false,
        adminAuthentication: 'custom',
        preRouterHook: googleAdminAuth,
      };
      
      unleash.start(options).then(instance => {
        console.log(
          `Unleash started on http://localhost:${instance.app.get('port')}`,
        );
      });
`

**Comment by ivarconr** [comment]
My question was more how do you override the existing index.js? Could you not also manually add required dependencies?

**Comment by evanstucker-hates-2fa** [comment]
I've written a Helm chart that uses a Kubernetes ConfigMap to map index.js code to the `/index.js` file in the container. I can continue to use my forked copy of this Docker image with those packages installed, but this Docker image would be much easier for your users to implement if it had these packages built into it. Similarly, I still need a place to put this Helm chart. It would make it incredibly easy for people using Kubernetes to implement Unleash.

**Comment by evanstucker-hates-2fa** [comment]
If you'd like to discuss further, I'm happy to video chat and screen share. Feel free to contact me at evans.tucker@gmail.com.

**Comment by ivarconr** [comment]
Sorry, I totally forgot about this issue in all the other things happening in the world right now. It makes sense what you write. Would you mind sharing your helm-chart for Unleash?

**Comment by rafaeelaudibert** [comment]
It would be awesome if the helm chart was shared, @evanstucker-hates-2fa. Maybe besides this repo we could have a repo with everything configured for K8S?

**Comment by evanstucker-hates-2fa** [comment]
@rafaeelaudibert Sorry for the very slow reply - this got lost in my inbox. I wrote a helm chart. You can find it here: https://github.com/Unleash/helm-charts

**Comment by ericwooley** [comment]
While the helm chart thing is cool. 

It would be nice to have a more generic solution that doesn't require writing your own js file. Like env variables/volumes/files for google auth, preshared key, etc...

Since I need to write my own anyways, maybe I'll make a PR for that. The dependencies are already added. ha

**Pull request merged**
